### ISSUE TITLE
Update to latest React and Bootstrap (4)

### ISSUE THREAD

**Issue by lgkonline** [lgkonline/react-bootstrap-ribbon#1]

**Comment by akoskm** [comment]
Hi, any plans to upgrade to bootstrap 4?

**Comment by akoskm** [comment]
Anyone looking for bootstrap 4 version, here's a fork: https://github.com/jonathanlazaro1/react-bootstrap4-ribbon.

**Comment by lgkonline** [comment]
I'm now working on a new version which is using Bootstrap 4. It should be ready to use the next days.

**Comment by lgkonline** [comment]
@akoskm The Ribbon component is now compatible with Bootstrap 4 🥳
Check out the new website: https://ribbon.lgk.io/

**Comment by akoskm** [comment]
Awesome, thank you @lgkonline 👏
